; Solomon's Key NES ROM Disassembly
; PRG CRC32 checksum: 0771c34f
; CHR CRC32 checksum: fad8a464
; Overall CRC32 checksum: 40684e95
; Code base address: $8000
; author: ninespaces
; ROM map info from https://www.romhacking.net/documents/902/
; see also: https://docs.google.com/spreadsheets/d/1EKLm0fHJ-rp5udljMHu-O83MaiY2XTmdcYA7ya-KYNQ/edit?usp=sharing
; preservation baseline imported from:
; https://github.com/rbmichael/solomons_key_disassembly

.setcpu "6502x"
.segment "HEADER"

    .byte "NES", $1a  ; Magic string that always begins an iNES header
    .byte $02  ; Number of 16KB PRG-ROM banks
    .byte $04  ; Number of 8KB CHR-ROM banks
    .byte $30  ; Control bits 1
    .byte $00  ; Control bits 2
    .byte $00  ; Number of 8KB PRG-RAM banks
    .byte $00  ; Video format NTSC/PAL

.include "memory/hardware.inc"
.include "memory/ram.inc"

.include "system/nmi.asm"
.include "system/controller_input.asm"
.include "game/object_update.asm"
.include "game/object_motion.asm"
.include "game/object_collision.asm"
.include "game/object_animation.asm"
.include "game/object_collision_dispatch.asm"
.include "data/object_collision_handlers.asm"
.include "game/object_collision_response.asm"
.include "game/object_y_thirteen_clamp.asm"
.include "game/object_y_clamp.asm"
.include "game/object_x_left_clamp.asm"
.include "game/object_x_right_clamp.asm"
.include "game/object_motion_animation.asm"
.include "graphics/ppu_update_stream.asm"
.include "graphics/ppu_attribute_read.asm"
.include "data/pre_startup_padding.asm"
.include "system/startup.asm"
.include "system/scheduler.asm"
.include "system/pause_thread.asm"
.include "system/sound_effect_queue.asm"
.include "system/ppu_update_buffer.asm"
.include "system/jump_with_params.asm"
.include "data/room_load_palette.asm"
.include "game/room_clear_thread.asm"
.include "data/room_clear.asm"
.include "game/room_time_bonus.asm"
.include "game/room_load_thread.asm"
.include "data/room_load.asm"
.include "game/new_game_state_reset.asm"
.include "system/gameplay_delay_setup.asm"
.include "system/masked_ram_wait.asm"
.include "system/secondary_thread_reset.asm"
.include "game/room_door_key_update.asm"
.include "game/room_intro.asm"
.include "data/room_intro.asm"
.include "game/two_digit_number.asm"
.include "game/room_entry_animation.asm"
.include "data/room_entry_animation.asm"
.include "game/transition_object_orbit.asm"
.include "game/transition_orbit_position.asm"
.include "game/transition_orbit_scale.asm"
.include "game/quarter_sine.asm"
.include "data/quarter_sine.asm"
.include "graphics/static_ppu_update_queue.asm"
.include "data/static_ppu_update_streams.asm"
.include "game/room_enemy_load.asm"
.include "graphics/room_map_render.asm"
.include "game/room_transition_reset.asm"
.include "graphics/nametable_clear.asm"
.include "data/nametable_clear.asm"
.include "graphics/full_nametable_clear.asm"
.include "graphics/ppu_address.asm"
.include "graphics/direct_ppu_transfer.asm"
.include "graphics/ppu_data_writers.asm"
.include "data/repeated_ppu_patterns.asm"
.include "graphics/room_nametable_frame.asm"
.include "game/room_item_decode.asm"
.include "data/room_item_decode.asm"
.include "game/room_block_decode.asm"
.include "game/dana_actions.asm"
.include "system/counter_wait.asm"
.include "game/map_interactions.asm"
.include "game/coordinate_object_overlap.asm"
.include "graphics/room_map_cell_update.asm"
.include "graphics/room_map_ppu_address.asm"
.include "data/main_thread_padding.asm"
.include "game/coordinate_conversion.asm"
.include "game/main_thread.asm"
.include "game/demon_mirror_activation.asm"
.include "game/demon_mirror_schedule.asm"
.include "game/demon_mirror_spawn.asm"
.include "game/demon_mirror_initialization.asm"
.include "game/timer.asm"
.include "data/timer_warning.asm"
.include "game/timer_item_effects.asm"
.include "game/inventory_item_effects.asm"
.include "data/item_scores.asm"
.include "game/auxiliary_effect.asm"
.include "game/score.asm"
.include "game/timer_display.asm"
.include "game/enemy_movement.asm"
.include "game/enemy_ai_dispatch.asm"
.include "graphics/fireball_inventory_display.asm"
.include "data/fireball_inventory_display.asm"
.include "game/fireball_lifetime.asm"
.include "game/enemy_initialization.asm"
.include "game/enemy_type_configuration.asm"
.include "data/enemy_types.asm"
.include "game/enemy_ai_handlers.asm"
.include "game/enemy_position.asm"
.include "game/enemy_pointers.asm"
.include "game/enemy_slot_allocation.asm"
.include "data/enemy_record_pointers.asm"
.include "game/enemy_deactivation.asm"
.include "game/current_enemy_deactivation.asm"
.include "game/active_object_states.asm"
.include "game/object_pointer.asm"
.include "game/non_dana_object_deactivation.asm"
.include "graphics/gameplay_hud.asm"
.include "data/gameplay_hud.asm"
.include "graphics/score_display.asm"
.include "preservation/prg.asm"
.include "graphics/chr.asm"
